name: CI - Publish Package

on:
  push:
    branches:
      - master

  publish-grp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: NodeJs Environment
        uses: actions/setup-node@v3.2.0
        with:
          node-version: 16

      - name: Get Package Version
        run: npm version ${{ github.event.release.tag_name }}

      - name: Install Dependencies
        run: yarn install

      - name: Build Package
        run: npm run build

      - name: Test Package
        run: npm run test

      - name: Set package registry GRP
        run: npm config set registry https://npm.pkg.github.com

      - name: Github package registry authentication
        run: npm set //npm.pkg.github.com/:_authToken ${{ secrets.GHP_PACKAGES_TOKEN }}

      - name: Publish Packages on NPM
        run: npm publish
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}