name: CI - Publish Package

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: NodeJs Environment
        uses: actions/setup-node@v3.2.0
        with:
          node-version: 16

      - name: Get Package Version
        run: npm version ${{ github.event.release.tag_name }}

      - name: Install Dependencies
        run: yarn install

      - name: Test Package
        run: npm run test

  publish-grp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: NodeJs Environment
        uses: actions/setup-node@v3.2.0
        with:
          node-version: 16

      - name: Get Package Version
        run: npm version ${{ github.event.release.tag_name }}

      - name: Install Dependencies
        run: yarn install

      - name: Build Package
        run: npm run build

      - name: Test Package
        run: npm run test

      - name: Set package registry GRP
        run: npm config set registry https://npm.pkg.github.com

      - name: Github package registry authentication
        run: npm set //npm.pkg.github.com/:_authToken ${{ secrets.PUBLISH_TOKEN_GRP }}

      - name: Publish Packages on NPM
        run: npm publish
  
  publish-npm:
    runs-on: ubuntu-latest
    needs: [publish-grp]
    steps:
      - uses: actions/checkout@v2

      - name: NodeJs Environment
        uses: actions/setup-node@v3.2.0
        with:
          node-version: 16

      - name: Get Package Version
        run: npm version ${{ github.event.release.tag_name }}

      - name: Install Dependencies
        run: yarn install

      - name: Build Package
        run: npm run build

      - name: Test Package
        run: npm run test

      - name: Github package registry authentication
        run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"

      - name: Publish Packages on NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  update-version:
    runs-on: ubuntu-latest
    needs: [publish-npm]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}

      # set up git since we will later push to the repo
      - run: git config --global user.name "GitHub CD bot"
      - run: git config --global user.email "dev@brainylab.com.br"

      - run: npm version ${{ github.event.release.tag_name }}

      - run: git push
        env:
          # The secret is passed automatically. Nothing to configure.
          github-token: ${{ secrets.GITHUB_TOKEN }}